export type ApiUrls = {
  GET: {
    PERFIL_CV_ID: string;
    PERFIL_CV_I18N_ID: string;
    LINK_CV_ID: string;
    LINKS_CV: string;
    HABILITAT_ID: string;
    HABILITATS: string;
    EXPERIENCIA_ID: string;
    EXPERIENCIES: string;
    EXPERIENCIA_I18N_ID: string;
    EXPERIENCIA_I18N_DETALL_ID: string;
    EDUCACIO_ID: string;
    EDUCACIO_CV: string;
    EDUCACIO_I18N_ID: string;
    EDUCACIO_I18N_DETALL_ID: string;
    PERSONA_DETALL_SLUG: (slug: string) => string;
    CIUTAT_ID: string;
    PAIS_ID: string;
    CLIENTS: string;
    CLIENT_ID: string;
    FACTURACIO_CLIENTS: (id: number) => string;
    INVOICE_PDF: (id: number, lang: 'ca' | 'es' | 'en' | 'it') => string;
    FACTURA_CLIENT_ID: string;
    FACTURA_CLIENT_PRODUCTE_ID: (id: string) => string;
    TEMA_ID: string;
    SUBTEMA_ID: string;
    LINK_ID: string;
    AGENDA_ID: string;
    PERSONES_GRUPS_ID: string;
    PROJECTE_ID: string;
    TASK_ID: string;
    PROJECTE_DETALLS: string;
    PROJECTE_TASQUES: string;
    BLOG_ARTICLE_ID: string;
    HISTORIA_CURS_ARTICLE_ID: string;
    EMISSORS_FACTURES: string;
    EMISSOR_ID: string;
    PRODUCTES: string;
    PRODUCTE_ID: (id: string) => string;
    DESPESES: (id: number, tipus_despesa: string) => string;
    PROVEIDORS: string;
    PROVEIDOR_ID: string;
    DESPESA_ID: string;
  };
  POST: {
    PERFIL_CV: string;
    PERFIL_CV_I18N: string;
    LINK_CV: string;
    HABILITAT: string;
    EXPERIENCIA: string;
    EXPERIENCIA_I18N: string;
    EDUCACIO_I18N: string;
    EDUCACIO_CV_POST: string;
    PERSONA: string;
    CIUTAT: string;
    PAIS: string;
    CLIENT: string;
    FACTURA_CLIENT: string;
    FACTURA_CLIENT_PRODUCTE: string;
    ENVIAR_FACTURA_EMAIL: (id: number, lang: 'ca' | 'es' | 'en' | 'it') => string;
    TEMA: string;
    SUBTEMA: string;
    LINK: string;
    AGENDA_ESDEVENIMENT: string;
    PERSONES_GRUPS: string;
    PROJECTE: string;
    TASCA: string;
    BLOG_ARTICLE: string;
    HISTORIA_CURS_ARTICLE: string;
    EMISSOR: string;
    PRODUCTE: string;
    PROVEIDOR: string;
    DESPESA: string;
  };
  PUT: {
    PERFIL_CV: string;
    PERFIL_CV_I18N: string;
    LINK_CV: string;
    HABILITAT: string;
    EXPERIENCIA: string;
    EXPERIENCIA_I18N: string;
    EDUCACIO_I18N: string;
    EDUCACIO_CV_POST: string;
    PERSONA: (id: string) => string;
    CIUTAT: string;
    PAIS: (id: string) => string;
    CLIENT: string;
    FACTURA_CLIENT: string;
    FACTURA_CLIENT_PRODUCTE: string;
    TEMA: string;
    SUBTEMA: string;
    LINK: string;
    AGENDA_ESDEVENIMENT: string;
    PERSONES_GRUPS: string;
    PROJECTE: string;
    TASCA: string;
    BLOG_ARTICLE: string;
    HISTORIA_CURS_ARTICLE: string;
    EMISSOR: string;
    PRODUCTE: string;
    PROVEIDOR: string;
    DESPESA: string;
  };
  DELETE: {};
};
